on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Cache installed dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: make prepare_in_docker
      - name: Build add-on
        run: make build_in_docker
      - name: Save built add-on
        uses: actions/upload-artifact@v2
        with:
          name: build_web-ext
          path: build/web-ext
          retention-days: 30
      - name: Save code documentation
        uses: actions/upload-artifact@v2
        with:
          name: build_docs
          path: build/docs
          retention-days: 30
  release:
    runs-on: ubuntu-20.04
    needs: build
    steps:
      - name: Get git information
        id: git_info
        run: echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ steps.git_info.outputs.SOURCE_TAG }}
          body: ''
      - name: Download built add-on for release
        uses: actions/download-artifact@v2
        with:
          name: build_web-ext
          path: build/web-ext
      - name: Download documentation for release
        uses: actions/download-artifact@v2
        with:
          name: build_docs
          path: build/docs
      - name: Prepare release packages
        run: |
          cp ./build/web-ext/mozilla/pontoon_add-on-*.zip "./pontoon_add-on-${{ steps.git_info.outputs.SOURCE_TAG }}-mozilla.zip"
          cp ./build/web-ext/chrome/pontoon_add-on-*.zip "./pontoon_add-on-${{ steps.git_info.outputs.SOURCE_TAG }}-chrome.zip"
          tar -cvf ./docs.tar.gz ./build/docs
      - name: Upload Firefox version to GitHub
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pontoon_add-on-${{ steps.git_info.outputs.SOURCE_TAG }}-mozilla.zip
          asset_name: pontoon_add-on-${{ steps.git_info.outputs.SOURCE_TAG }}-mozilla.zip
          asset_content_type: application/zip
      - name: Upload Chrome version to GitHub
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./pontoon_add-on-${{ steps.git_info.outputs.SOURCE_TAG }}-chrome.zip
          asset_name: pontoon_add-on-${{ steps.git_info.outputs.SOURCE_TAG }}-chrome.zip
          asset_content_type: application/zip
      - name: Upload documentation to GitHub
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./docs.tar.gz
          asset_name: docs.tar.gz
          asset_content_type: application/gzip
